[project]
name = "md4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clu>=0.0.12",
    "datasets>=4.0.0",
    "distrax>=0.1.5",
    "grain>=0.2.11",
    "huggingface-hub>=0.33.2",
    "jax>=0.6.2",
    "matplotlib>=3.10.3",
    "ml-collections>=1.1.0",
    "polars>=1.31.0",
    "rdkit>=2025.3.3",
    "seaborn>=0.13.2",
    "tensorflow>=2.19.0",
    "tensorflow-datasets>=4.9.9",
    "tf-keras>=2.19.0",
    "transformers>=4.53.1",
]
